language: php

php:
  - 5.6
  - 7.0

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs

cache:
  directories:
    - vendor/

notifications:
  email: false